services:
  backend:
    build: ./back-end
    ports:
      - "4000:4000"
    volumes:
      - ./back-end:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./site
    ports:
      - "3000:80"
    depends_on:
      - backend

  # Optional DB example
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolat-db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: